package com.mcbanners.bannerapi.banner;

public enum BannerType {
    SPONGE_AUTHOR,
    SPONGE_RESOURCE,
    SPIGOT_AUTHOR,
    SPIGOT_RESOURCE,
    MINECRAFT_SERVER,
    CURSEFORGE_AUTHOR,
    CURSEFORGE_RESOURCE,
    MODRINTH_AUTHOR,
    MODRINTH_RESOURCE,
    MCMARKET_AUTHOR,
    MCMARKET_RESOURCE,
    MCMARKET_MEMBER,
    POLYMART_AUTHOR,
    POLYMART_RESOURCE
}
